spring:
  datasource:
    url: jdbc:mysql://192.168.1.249:3306/civil_military?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: pustian
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 2
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
    filters: stat
    validationQuery: SELECT 'x'
member:
  login:
    # 6min
    lockInterval: 2
    # 允许连续错误输入密码次数,3次错误输入锁定。必须>0
    allowedErrorTime: 3
