server:
  port: 8001
  # 最大连接数和最大并发数默认是10000和200
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    max-connections: 20000
  # 对外提供的http超时时间设置

spring:
  profiles:
    active: dev
  application:
    name: member
